# Generated by Django 5.1.1 on 2026-02-13 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIServiceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("openrouter", "OpenRouter"),
                            ("fallback", "Fallback System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=100, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(blank=True, null=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_used"],
                "indexes": [
                    models.Index(
                        fields=["service_name"], name="chatbot_app_service_302f0d_idx"
                    ),
                    models.Index(
                        fields=["last_used"], name="chatbot_app_last_us_460b7f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="chatbot_app_session_ffcd8e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="chatbot_app_created_31c6e5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("active_sessions", models.PositiveIntegerField(default=0)),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("memory_usage_mb", models.FloatField(blank=True, null=True)),
                ("cpu_usage_percent", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="chatbot_app_timesta_e4c088_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("bot", "Bot Message"),
                            ("system", "System Message"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_fallback", models.BooleanField(default=False)),
                (
                    "ai_service_used",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot_app.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="chatbot_app_session_27a646_idx",
                    ),
                    models.Index(
                        fields=["message_type"], name="chatbot_app_message_ac9b98_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="chatbot_app_timesta_374104_idx"
                    ),
                ],
            },
        ),
    ]
